# Generated by Django 3.1.4 on 2020-12-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tel',
            field=models.CharField(max_length=50),
        ),
    ]
