# Generated by Django 3.1.4 on 2020-12-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique_for_date='created'),
        ),
    ]
